# Generated by Django 2.2.5 on 2019-09-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='engine',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Двигатель'),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='foto_car/', verbose_name='Изображение товара'),
        ),
    ]
