# Generated by Django 2.2.5 on 2019-09-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190906_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='transmission',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Коробка передач'),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Марка'),
        ),
    ]
