# Generated by Django 2.2.5 on 2019-09-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_article_author_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание'),
        ),
    ]
