# Generated by Django 2.2.5 on 2019-09-10 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20190910_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='new',
        ),
        migrations.AddField(
            model_name='comments',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forum.Product', verbose_name='Автомобили'),
            preserve_default=False,
        ),
    ]
